In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from scipy import stats
from scipy.stats import norm, t, ttest_1samp, ttest_ind, mannwhitneyu, shapiro, kstest

import statsmodels.api as sm

In [5]:
file_path =r'C:/Users/offic/OneDrive/Рабочий стол/Study/Academica/Финальный проект/Тестовое задание/Данные для тестового задания.xlsx'

xls = pd.ExcelFile(file_path)

xls.sheet_names

['Данные об аудитории', 'Данные АБ тестов', 'Листеры']

In [6]:
df = pd.read_excel(file_path, sheet_name='Данные об аудитории')
df.head()

        date                               user_id  view_adverts
0 2023-11-11  8c020470-8461-11ed-83d0-552e8cc749d6            13
1 2023-11-18  5875f070-7b92-11ee-a6fb-8b298e83f4f7            14
2 2023-11-29  3c2d27c0-4fd6-11eb-b89f-2ffb31b67dd6            21
3 2023-11-29  234a96d0-ad16-11ed-a2e6-793ddfeeba1f            23
4 2023-11-29  4d07c180-644f-11eb-879c-b7c02edf4f37            12

In [7]:
mau = df['user_id'].nunique()
print(mau)

7639

In [8]:
dau = df.groupby('date')['user_id'].nunique().mean()
print(dau)

560.4666666666667

In [9]:
# пользователи 1 ноября
day1 = df[df['date'] == '2023-11-01']['user_id'].unique()

# пользователи 2 ноября
day2 = df[df['date'] == '2023-11-02']['user_id'].unique()

# сколько вернулось
returned = len(set(day1) & set(day2))

# retention
retention = returned / len(day1) * 100

print(retention)

26.64526484751204

In [10]:
total_users = df['user_id'].nunique()

users_with_ads = df[df['view_adverts'] > 0]['user_id'].nunique()

conversion = users_with_ads / total_users * 100

print(conversion)

46.31496269145176

In [14]:
avg_ads = df.groupby('user_id')['view_adverts'].sum().mean()
print(avg_ads)

2.8687000916350307

In [12]:
promoters = 1200
detractors = 500
total = 2000

nps = (promoters/total - detractors/total) * 100
print(nps)

35.0

In [17]:
ab = pd.read_excel(file_path, sheet_name='Данные АБ тестов')
ab.head()

   experiment_num experiment_group   user_id  revenue
0               1             test     38456      520
1               1          control  13125924      806
2               1          control   9761984        0
3               1             test  11387012      208
4               1             test  18319648      104

In [18]:
ab['experiment_num'].unique()

array([1, 2, 3])

In [20]:
for exp in ab['experiment_num'].unique():
    data_exp = ab[ab['experiment_num'] == exp]
    
    group_test = data_exp[data_exp['experiment_group'] == 'test']['revenue']
    group_control = data_exp[data_exp['experiment_group'] == 'control']['revenue']
    
    stat, p = ttest_ind(group_test, group_control, equal_var=False)
    
    print(f'Experiment {exp}: p-value = {p}')

Experiment 1: p-value = 0.688966190624939
Experiment 2: p-value = 0.0011282266247294027
Experiment 3: p-value = 0.06031548002841902

In [21]:
listings = pd.read_excel(file_path, sheet_name='Листеры')
listings.head()

   user_id       date  cnt_adverts  age  cnt_contacts  revenue
0      100 2022-01-01            6   21           119       53
1      100 2022-01-02            2   21           200       18
2      100 2022-01-03            6   21           193       42
3      100 2022-01-04            2   21           143       38
4      100 2022-01-05            2   21           190       40

In [23]:
listings['revenue'].mean()

np.float64(30.70253164556962)

In [24]:
listings['age'].median()

28.0